# Generated by Django 4.2.4 on 2024-02-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userlibraryaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibraryaccount',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
