# Generated by Django 4.2.4 on 2024-02-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookposts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Post',
            new_name='post',
        ),
    ]
